CREATE TABLE tags (
  id INT UNSIGNED AUTO_INCREMENT,
  tag VARCHAR(255),
  PRIMARY KEY (id)
);

CREATE TABLE receipts (
  id INT UNSIGNED AUTO_INCREMENT,
  uploaded TIME DEFAULT CURRENT_TIME(),
  merchant VARCHAR(255),
  amount DECIMAL(12,2),
  receipt_type INT UNSIGNED,
  PRIMARY KEY (id)
);

CREATE TABLE receipts_tags (
  id INT UNSIGNED AUTO_INCREMENT,
  receiptId INT UNSIGNED,
  tagId INT UNSIGNED,
  PRIMARY KEY (id),
  FOREIGN KEY (receiptId) REFERENCES receipts(id),
  FOREIGN KEY (tagId) REFERENCES tags(id),
);
