CREATE TABLE tag (
  id INT UNSIGNED AUTO_INCREMENT,
  tagName VARCHAR(255),
  PRIMARY KEY (id)
);

CREATE TABLE receipt (
  id INT UNSIGNED AUTO_INCREMENT,
  uploaded TIME DEFAULT CURRENT_TIME(),
  merchant VARCHAR(255),
  amount DECIMAL(12,2),
  receipt_type INT UNSIGNED,
  PRIMARY KEY (id)
);

CREATE TABLE receipt_tag (
  id INT UNSIGNED AUTO_INCREMENT,
  receiptId INT UNSIGNED,
  tagId INT UNSIGNED,
  PRIMARY KEY (id),
  FOREIGN KEY (receiptId) REFERENCES receipt(id),
  FOREIGN KEY (tagId) REFERENCES tag(id),
);
